#!/bin/bash

# GitHub Actions Security Pinning Script
# This script pins all GitHub Actions in workflow files to their commit SHAs

set -e

echo "🔐 GitHub Actions Security Pinning"
echo "=================================="

# Check if Node.js is available
if ! command -v node &> /dev/null; then
    echo "❌ Error: Node.js is not installed or not in PATH"
    exit 1
fi

# Check if we're in the right directory
if [ ! -f "scripts/pin-github-actions.js" ]; then
    echo "❌ Error: This script must be run from the repository root"
    echo "   Expected to find: scripts/pin-github-actions.js"
    exit 1
fi

# Check if .github/workflows directory exists
if [ ! -d ".github/workflows" ]; then
    echo "ℹ️  No .github/workflows directory found. Nothing to pin."
    exit 0
fi

# Install dependencies if needed
if [ ! -d "node_modules" ]; then
    echo "📦 Installing dependencies..."
    npm install --legacy-peer-deps --silent
fi

# Run the pinning script
echo "🔍 Scanning for unpinned GitHub Actions..."

if [ "${1:-}" = "--dry-run" ]; then
    echo "🧪 Running in dry-run mode..."
    node scripts/pin-github-actions.js --dry-run --verbose
else
    node scripts/pin-github-actions.js --verbose
    
    # Check if any changes were made
    if git diff --quiet .github/workflows/; then
        echo "✅ No changes needed - all actions were already pinned"
    else
        echo "📝 Changes detected. Committing pinned actions..."
        git add .github/workflows/
        git commit -m "Pin GitHub Actions to full-length commit SHAs for improved security

- Updated workflow files to use commit SHAs instead of tags
- This prevents supply chain attacks where tags could be moved to malicious commits
- Generated by: scripts/pin-github-actions.js"
        echo "✅ Changes committed successfully"
    fi
fi

echo "🎯 Done!"