name: APIsec Scan

on:
  pull_request:

jobs:
  apisec_scan:
    runs-on: ubuntu-latest
    steps:
      - name: APIsec scan
        uses: apisec-inc/apisec-run-scan@025432089674
        with:
          apisec-username: ${{ secrets.apisec_username }}
          apisec-password: ${{ secrets.apisec_password }}
          apisec-project: "VAmPI"
          sarif-result-file: "apisec-results.sarif"
      - name: Import results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ./apisec-results.sarif
