name: CI/CD Pipeline

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Auto assign reviewers
        uses: kentaro-m/auto-assign-action@v1
        with:
          reviewers: 'your-reviewer-username'