name: Branch Protection Setup

on:
  workflow_dispatch: # Manual trigger only
  repository_dispatch:
    types: [setup-branch-protection]

permissions:
  contents: read
  administration: write

jobs:
  setup-branch-protection:
    name: Setup Branch Protection Rules
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup branch protection for main
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          try {
            const { owner, repo } = context.repo;
            
            // Setup branch protection rules for main branch
            await github.rest.repos.updateBranchProtection({
              owner,
              repo,
              branch: 'main',
              required_status_checks: {
                strict: true,
                contexts: [
                  'Code Linting',
                  'Security Scanning', 
                  'Build Contracts',
                  'Run Tests'
                ]
              },
              enforce_admins: false,
              required_pull_request_reviews: {
                required_approving_review_count: 1,
                dismiss_stale_reviews: true,
                require_code_owner_reviews: false,
                require_last_push_approval: true
              },
              restrictions: null,
              allow_force_pushes: false,
              allow_deletions: false,
              block_creations: false,
              required_conversation_resolution: true
            });
            
            console.log('Branch protection rules successfully applied to main branch');
          } catch (error) {
            console.error('Error setting up branch protection:', error);
            // Don't fail the workflow if branch protection setup fails
            // as it might require admin permissions
          }